version: '3'


services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    env_file:
      - .env
    container_name: vai
    volumes:
      - ./postgres:/var/lib/postgresql/data